### ISSUE TITLE
文章列表和TOC侧边栏目录异常

### ISSUE THREAD

**Issue by lonsty** [imkundev/halo-theme-fantastic#11]
文章中的有序列表、无序列表会直接被剪切当成侧边栏目录。

能否先将TOC功能去掉，让Markdown可以正常使用列表编辑

**Comment by MrLawrenc** [comment]
我也遇到了 作者的回答： 你好，文章Toc是故意放到右边的，现在正在做一个用JS生成Toc的方式以代替Halo系统自带的Toc生成方式，下一个版本会更新。

**Comment by kunpehx** [comment]
fixed.
