### ISSUE TITLE
Swiper is not defined

### ISSUE THREAD

**Issue by Przeblysk** [imkundev/halo-theme-fantastic#12]
Swiper is not defined
轮播组件好像炸裂了

**Comment by kunpehx** [comment]
@Przeblysk 麻烦提供一下浏览器是哪个版本的

**Comment by Przeblysk** [comment]
是文章只有一篇并且没有设置为置顶的情况。如果只有一篇置顶的文章，下面的最新文章排版也会有问题，因为中间的文章列表就没内容了。不过这些只要文章内容多了就不存在了，并且设置好置顶，感谢开发者提供那么好看的主题👻👻👻
