### ISSUE TITLE
个人说明过长会超出父布局框

### ISSUE THREAD

**Issue by Przeblysk** [imkundev/halo-theme-fantastic#13]
![image](https://user-images.githubusercontent.com/18001272/69307200-e23af900-0c64-11ea-838a-4319e05cef60.png)

**Comment by kunpehx** [comment]
可以把文字减少一点，设计的时候本来就不是放长文本的

**Comment by Przeblysk** [comment]
好像有偏移
![image](https://user-images.githubusercontent.com/18001272/69430912-92962380-0d71-11ea-97fe-64802712a613.png)

**Comment by kunpehx** [comment]
请合理设置个人签名
ignore
