### ISSUE TITLE
请问主题TOC目前是否可以支持4级标题？

### ISSUE THREAD

**Issue by xzhuz** [imkundev/halo-theme-fantastic#15]
markdown 现在4级标题无法展示出来。

比如：
#### 4级标题

**Comment by kunpehx** [comment]
@xebcxc 目前不支持。文章的toc是用Halo系统自带的渲染出来的。考虑把toc用js生成，下个版发布。

**Comment by xzhuz** [comment]
@imkundev https://github.com/tscanlin/tocbot 这个js插件很好用

**Comment by JohnNiang** [comment]
> markdown 现在4级标题无法展示出来。
> 
> 比如：
> 
> #### 4级标题

下一个版本 v1.1.3 将会支持所有级别的 TOC。

**Comment by kunpehx** [comment]
fixed
