### ISSUE TITLE
主题使用建议

### ISSUE THREAD

**Issue by Alicyu1024** [imkundev/halo-theme-fantastic#2]
1. 页面日志模板没有(不重要,有最好)
2. 主页多个置顶文章希望能加个自动切换
3. 文章页面右侧边栏, 相关文章和相关推荐是否重复显示?
4. 左侧边栏个人资料的高度和置顶文章高度一致是否看起来更和谐一点?
~~5. 文章页面右侧的TOC目录显示好像有问题, 我在next主题显示目录正常但是这个就乱了.~~(加了[TOC]显示正常了, 以前nextT主题好像会自动识别出目录, 而且可以点击目录跳转到指定位置, 感觉点击目录跳转真的很好用, 看长篇文章会很方便)
6. 文章代码部分上下和左右的滑动条可以只用那种细的色块(比如主页的蓝色渐变色)来代替感觉会更和文章贴近
7. 个人很喜欢的一个主题, 以上只是个人喜好观感, 如果觉得可以那就很棒, 如果和你的想法冲突, 请忽视! 谢谢!

**Comment by erdengk** [comment]
赞同第2、3、4、6点，很喜欢这个主题，祝愿这个主题越变越好

**Comment by kunpehx** [comment]
@Alicyu1024 @wannengdek  谢谢Alicyu1024的宝贵建议。
    **针对以上建议，2 4 两点可能会在未来添加**
## 说明
关于第1点，原有想法时可把日志在首页上作为一个widgt显示，由于halo系统没有日志对应该的标签，所有不能在首页展示，目前还在想怎么把日志展示出来，只有一个内容可显示，这样日志个人感觉用的地方不多，可以反驳🙂️。
关于第3点，由于右侧展示是取的当前文章的分类下的文章和当前文件第一个标签下的文章，从效率上考，暂时不做调整。
关于第5点，我个人觉得这样做的太花哨且不能带更好的视觉效果。
## 最后
感谢 @Alicyu1024 @wannengdek ，有你们才让Halo系统和fantastic主题变得更完美。

**Comment by Alicyu1024** [comment]
超级赞同你的日志想法, 如果能放到首页的一个小框展示出来最新的日志那就太棒了, 这才完全体现了日志的功能啊, 哈哈, 我去halo下面提issue建议, 看能不能加上一个标签

**Comment by congjinruo** [comment]
博主你的主题很好，不过我也有点小意见：  
代码块区域 显式滚动条怎么去除哇  
暗黑模式翻页按钮也适配下就好了  
侧边toc滑动到底下就不能点击了

**Comment by kunpehx** [comment]
@congjinruo 
刚你提的几点优化都很好，现在已经优化。赶快更新试试吧。

**Comment by congjinruo** [comment]
> @congjinruo
> 刚你提的几点优化都很好，现在已经优化。赶快更新试试吧。

迅捷、高效、厉害，赞一个👍

**Comment by blackleexu** [comment]
> 博主你的主题很好，不过我也有点小意见：
> 代码块区域 显式滚动条怎么去除哇
> 暗黑模式翻页按钮也适配下就好了
> 侧边toc滑动到底下就不能点击了

弱弱的问一句，暗黑主题怎么开，预览不到效果
