### ISSUE TITLE
主题移植申请

### ISSUE THREAD

**Issue by adlered** [imkundev/halo-theme-fantastic#29]
作者你好，我是开源项目 [Bolo 菠萝博客](https://github.com/adlered/bolo-solo) 的项目维护者。  
觉得 `halo-theme-fantastic` 这个主题很绝妙，希望可以获得作者的授权移植到我们的博客系统当中 :smile: 万分感谢！

**Comment by kunpehx** [comment]
谢谢对此主题的认可，我也希望主题能应用到更多的博客平台，所以，可以进行移植和优化。

**Comment by adlered** [comment]
非常感谢！
