### ISSUE TITLE
文章缩略图显示不全的问题

### ISSUE THREAD

**Issue by lw2590** [imkundev/halo-theme-fantastic#3]
目前设置的部分文章“缩略图”显示不全的问题，请关注一下，比较喜欢这个主题，希望能尽快解决，谢谢。

**Comment by kunpehx** [comment]
@lw2590  你好，请问不全是什么意思? 有截图或者页面链接吗，帖上来看一下。

**Comment by lw2590** [comment]
![image](https://user-images.githubusercontent.com/15713296/67171724-e4523380-f3ea-11e9-8536-36132c9891a2.png)

**Comment by lw2590** [comment]
![image](https://user-images.githubusercontent.com/15713296/67171762-14013b80-f3eb-11e9-96d3-852c9aa727dc.png)
![image](https://user-images.githubusercontent.com/15713296/67171773-28453880-f3eb-11e9-85c8-241dfdcd1bb4.png)
可查看链接：www.liuwg.com

**Comment by kunpehx** [comment]
你好，看了一下您说的文章显示不完全的问题。
是这样的，为了页面美观，设置图样式为object-fit:fit。因为使用者设置的图片可能比例不一样，有2:1的，也有1:2的，所以会显示出来超长或超宽，这样可能会影响美观，如果你想完整显示图片，请在halo后台个性sytle.css文件中的`.card-normal .card .card-image img`选择器，添加`object-fit:fill !important`即可.

另外，我更新了Fantastic主题的使用说明，可以让你的博客更美观。参见 《[Fantastic 主题使用指南](https://www.imkun.dev/archives/Fantastic%20主题使用指南)》

**Comment by lw2590** [comment]
好的，非常感谢。
