### ISSUE TITLE
代码块格式错误

### ISSUE THREAD

**Issue by hwiechern** [imkundev/halo-theme-fantastic#4]
很喜欢的主题，让人惊喜的是还支持MathJax，但代码块格式错误
http://hwie.natappvip.cc/archives/hello-halo

**Comment by kunpehx** [comment]
@hwiechern 您使用的不是Fantastic主题，麻烦您不要提无关的问题，谢谢。

**Comment by hwiechern** [comment]
嗯嗯，已经修改了，是后端编辑器渲染问题。
