### ISSUE TITLE
Halo 安装fantastic 主题后 ,访问网站特别慢(平均加载需要22s 左右)

### ISSUE THREAD

**Issue by Acquaintant** [imkundev/halo-theme-fantastic#40]
1. 使用其他的主题均无此现象
2. 已经检查网络环境和服务器的设置
3.使用http2 进行加速

**Comment by xuzhougeng** [comment]
@Acquaintant 我觉得是这个主题用到了一些在国内被限制的网站，比如说字体和css 所对应的的如下页面

- use.fontawesome.com/releases/v5.4.1/css/all.css
- use.fontawesome.com/releases/v5.4.1/webfonts/fa-brands-400.woff2
- use.fontawesome.com/releases/v5.4.1/webfonts/fa-brands-400.woff
- use.fontawesome.com/releases/v5.4.1/webfonts/fa-brands-400.ttf
- use.fontawesome.com/releases/v5.4.1/webfonts/fa-solid-900.woff2
- use.fontawesome.com/releases/v5.4.1/webfonts/fa-solid-900.woff
- use.fontawesome.com/releases/v5.4.1/webfonts/fa-solid-900.ttf

还有里面还加载了一个谷歌的字体

```html
<link href="https://fonts.googleapis.com/css?family=Fira+Sans&display=swap" rel="stylesheet">
```

因为在国内，所以获取不了这些资源，导致速度极其缓慢。

**Comment by yhl452493373** [comment]
自己编辑主题文件，挨个ftl找，把他们换成对应的国内cdn。我改成
https://www.bootcdn.cn
这个cdn，很快。字体这种找不到的，直接删除
