### ISSUE TITLE
移动端头像偏移问题反馈

### ISSUE THREAD

**Issue by Alicyu1024** [imkundev/halo-theme-fantastic#5]
** 目前在我的页面发现, 个人头像向左边偏移, 没有居中显示, 还有, 移动端经常加载不出来头像, 电脑上可以正常显示, 但是电脑上Chrome检查切换为移动端设备显示也是头像位置向左偏移. 不知道是不是我一个人的问题? 

<img width="375" alt="问题反馈图" src="https://user-images.githubusercontent.com/21222184/67683718-d2fdbe00-f9cc-11e9-9a90-8f4a7cd44397.png">

**Comment by kunpehx** [comment]
@Alicyu1024 你好，我在下一次更新时会解决这个问题。

**Comment by kunpehx** [comment]
fixed
