### ISSUE TITLE
下一篇/上一篇文章提示

### ISSUE THREAD

**Issue by 3ys** [imkundev/halo-theme-fantastic#6]
第一篇文章的底部没有下一篇文章的链接提示；最后一篇文章的底部没有上一篇文章的链接提示；中间的文章都有。

**Comment by 3ys** [comment]
![Snipaste_2019-11-05_12-12-15](https://user-images.githubusercontent.com/49750670/68178084-8c5c2500-ffc5-11e9-8655-218ce9c9e29a.jpg)

**Comment by kunpehx** [comment]
fixed
