### ISSUE TITLE
markdown内容展示错位问题

### ISSUE THREAD

**Issue by MrLawrenc** [imkundev/halo-theme-fantastic#8]
编辑内容第一次使用“- ” 标签会出现该标签内的内容错位展示。

![image](https://user-images.githubusercontent.com/35510822/68271391-470a2700-009b-11ea-9a5d-7230aeaa84b7.png)
markdown内容：

[markdown.txt](https://github.com/imkundev/halo-theme-fantastic/files/3812696/markdown.txt)

**Comment by MrLawrenc** [comment]
图片挂了，，在下面这个位置的内容会错位：
- p 服务端端口
- pwd 服务端token校验

**Comment by kunpehx** [comment]
你好，文章Toc是故意放到右边的，现在正在做一个用JS生成Toc的方式以代替Halo系统自带的Toc生成方式，下一个版本会更新。

**Comment by MrLawrenc** [comment]
好的  非常感谢抽空解答，希望fantastic越来越好！

发送自 Windows 10 版邮件应用

发件人: Kun.Peng
发送时间: 2019年11月6日 17:28
收件人: imkundev/halo-theme-fantastic
抄送: MrLawrenc; Author
主题: Re: [imkundev/halo-theme-fantastic] markdown内容展示错位问题 (#8)

你好，文章Toc是故意放到右边的，现在正在做一个用JS生成Toc的方式以代替Halo系统自带的Toc生成方式，下一个版本会更新。
